### PR TITLE
Fix /setting bug, add xss checker gateway, depricate /time

### PR DESCRIPTION
**Pull request by chickemeeple**
Bug in which the sector.settings object returns values of true and false, therefore making a conditional false when the intended value was true

changed it to hasOwnProperty()

### CODE REVIEW

**Comment by chickemeeple** [comment]
Sorry for the typo, commit says but instead of bug 😅

**Comment by chickemeeple** [comment]
Now I can't steal peoples accounts :(

at least now junon gonna be free of xss
very very big vulnerability

**Comment by chickemeeple** [comment]
I have a habit of typing but :/

**Review by simpleyuji — APPROVED** [review]

**Comment by simpleyuji** [comment]
ok. thanks for the xss check. adding back the /time command tho

**Pull request merged**
